name: 'Remove from ProjectV2'
description: 'Removes an issue or pull request from a V2 project board'
author: 'jimgraham'
inputs:
  item-id:
    required: true
    description: 'The number of the issue or pull request to remove.'
  project-owner:
    required: false
    description: 'The owner of project. Defaults to the current repository owner.'
  project-number:
    required: true
    description: 'The number of the project board.'
  token:
    default: ${{ github.token }}
    description: >
      A token with access to the project board and issue or pull request.
      For projects outside of the current workflow's repository,
      a separate token is required.
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'trash-2'
  color: 'red'

